version: "3.1"
services:
  lvl:
    image: fredboat/lavalink:master
    restart: always
    volumes:
      - type: bind
        source: ./application.yml
        target: /opt/Lavalink/application.yml
  bot:
    build: .
    image: mydiscordbot
    depends_on:
      - lvl