version: "3.1"
services:
  lvl:
    image: fredboat/lavalink:dev
    restart: always
    volumes:
      - type: bind
        source: ./application.yml
        target: /opt/Lavalink/application.yml
  bot-music:
    build: .
    image: bot-music
    depends_on:
      - lvl