version: "3.1"
services:
  lvl:
    container_name: c-lvl
    image: fredboat/lavalink:dev
    restart: unless-stopped
    volumes:
      - azure-volume:/opt/Lavalink
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: 0.2G

  bot-music:
    build: .
    container_name: c-bot-music
    image: kellphy.azurecr.io/bot-music
    #image: bot-music
    restart: unless-stopped
    depends_on:
      - lvl
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 0.1G
      
volumes:
  azure-volume:
    driver: azure_file
    driver_opts:
      share_name: musicbot
      storage_account_name: kellphystorage